Add BypassBusinessLogicExecutionStepIds Limit
seanmcne/OrgDbOrgSettings pull request #120
Opened 2024-04-25 22:01 UTC by JosinaJoy

Add BypassBusinessLogicExecutionStepIds Limit

2024-04-25 22:26 UTC, JimDaly requested changes

2024-04-25 22:26 UTC, JimDaly commented on mspfedyn_/OrgDbOrgSettings/Settings.xml
> +  <orgSetting minSupportedVersion="9.2.24033.228" maxSupportedVersion="9.9999.9999.9999" name="BypassBusinessLogicExecutionStepIdsLimit" isOrganizationAttribute="false" min="" max="" defaultValue="3"
I think the supportURL  s/b https://aka.ms/NewBypassCustomLogicOptions

This will take people to the article we plan to publish soon... (It will 404 now, but we can fix that)

2024-04-25 22:30 UTC, JimDaly requested changes

2024-04-25 22:30 UTC, JimDaly commented on mspfedyn_/OrgDbOrgSettings/Settings.xml
> +  <orgSetting minSupportedVersion="9.2.24033.228" maxSupportedVersion="9.9999.9999.9999" name="BypassBusinessLogicExecutionStepIdsLimit" isOrganizationAttribute="false" min="" max="" defaultValue="3"
I think that `urlTitle="KB 2691237"` s/b 

`urlTitle="BypassBusinessLogicExecutionSteps optional parameter"`

2024-04-30 21:55 UTC, merged

2025-01-28 17:53 UTC, seanmcne commented
@JimDaly and @JosinaJoy - are you able to look into this #138 ?